baseURL = "/"
languageCode = "en-us"
title = "Bastien Boutonnet"
theme = "archie"
googleAnalytics = "G-2D14KHT48Y"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="light" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/bastienboutonnet"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/B_superhero/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/bastienboutonnet/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/bastien_superhero/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/homepage"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
